# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := cefclient
### Generated for copy rule.
$(builddir)/files/binding.html: TOOLSET := $(TOOLSET)
$(builddir)/files/binding.html: javacef/cefclient/res/binding.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/binding.html
$(builddir)/files/dialogs.html: TOOLSET := $(TOOLSET)
$(builddir)/files/dialogs.html: javacef/cefclient/res/dialogs.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/dialogs.html
$(builddir)/files/domaccess.html: TOOLSET := $(TOOLSET)
$(builddir)/files/domaccess.html: javacef/cefclient/res/domaccess.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/domaccess.html
$(builddir)/files/localstorage.html: TOOLSET := $(TOOLSET)
$(builddir)/files/localstorage.html: javacef/cefclient/res/localstorage.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/localstorage.html
$(builddir)/files/logo.png: TOOLSET := $(TOOLSET)
$(builddir)/files/logo.png: javacef/cefclient/res/logo.png FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/logo.png
$(builddir)/files/performance.html: TOOLSET := $(TOOLSET)
$(builddir)/files/performance.html: javacef/cefclient/res/performance.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/performance.html
$(builddir)/files/window.html: TOOLSET := $(TOOLSET)
$(builddir)/files/window.html: javacef/cefclient/res/window.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/window.html
$(builddir)/files/xmlhttprequest.html: TOOLSET := $(TOOLSET)
$(builddir)/files/xmlhttprequest.html: javacef/cefclient/res/xmlhttprequest.html FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/files/xmlhttprequest.html
$(builddir)/cef.pak: TOOLSET := $(TOOLSET)
$(builddir)/cef.pak: javacef/Resources/cef.pak FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/cef.pak
$(builddir)/devtools_resources.pak: TOOLSET := $(TOOLSET)
$(builddir)/devtools_resources.pak: javacef/Resources/devtools_resources.pak FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/devtools_resources.pak
$(builddir)/locales: TOOLSET := $(TOOLSET)
$(builddir)/locales: javacef/Resources/locales FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/locales
javacef_chromium_loader_gyp_cefclient_target_copies = $(builddir)/files/binding.html $(builddir)/files/dialogs.html $(builddir)/files/domaccess.html $(builddir)/files/localstorage.html $(builddir)/files/logo.png $(builddir)/files/performance.html $(builddir)/files/window.html $(builddir)/files/xmlhttprequest.html $(builddir)/cef.pak $(builddir)/devtools_resources.pak $(builddir)/locales

DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSING_CEF_SHARED' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-Ijavacef \
	-Ijavacef/chromium_loader \
	-I$(JAVA_HOME)/include \
	-I$(JAVA_HOME)/include/linux

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSING_CEF_SHARED' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-Ijavacef \
	-Ijavacef/chromium_loader \
	-I$(JAVA_HOME)/include \
	-I$(JAVA_HOME)/include/linux

OBJS := \
	$(obj).target/$(TARGET)/javacef/cefclient/cefclient.o \
	$(obj).target/$(TARGET)/javacef/cefclient/binding_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_app.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_app_delegates.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_handler.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_renderer.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_switches.o \
	$(obj).target/$(TARGET)/javacef/cefclient/dialog_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/dom_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/performance_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/performance_test_tests.o \
	$(obj).target/$(TARGET)/javacef/cefclient/scheme_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/string_util.o \
	$(obj).target/$(TARGET)/javacef/cefclient/window_test.o \
	$(obj).target/$(TARGET)/javacef/chromium_loader/jni_tools.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_handler_gtk.o \
	$(obj).target/$(TARGET)/javacef/cefclient/resource_util_linux.o \
	$(obj).target/$(TARGET)/javacef/cefclient/window_test_gtk.o \
	$(obj).target/$(TARGET)/javacef/cefclient/cefclient_gtk.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/javacef/libcef_dll_wrapper.a $(obj).target/javacef/gtk.stamp

# Make sure our actions/rules run before any of us.
$(OBJS): | $(javacef_chromium_loader_gyp_cefclient_target_copies)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(builddir)/cefclient: | $(javacef_chromium_loader_gyp_cefclient_target_copies)

# Preserve order dependency of special output on deps.
$(javacef_chromium_loader_gyp_cefclient_target_copies): | $(obj).target/javacef/libcef_dll_wrapper.a $(obj).target/javacef/gtk.stamp

LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-rpath,.

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-rpath,. \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	$(PWD)/javacef/$(BUILDTYPE)/libcef.so \
	-lgmodule-2.0 \
	-lgtk-x11-2.0 \
	-lgdk-x11-2.0 \
	-latk-1.0 \
	-lgio-2.0 \
	-lpangoft2-1.0 \
	-lpangocairo-1.0 \
	-lgdk_pixbuf-2.0 \
	-lcairo \
	-lpango-1.0 \
	-lfreetype \
	-lfontconfig \
	-lgobject-2.0 \
	-lgthread-2.0 \
	-lrt \
	-lglib-2.0

$(builddir)/cefclient: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/cefclient: LIBS := $(LIBS)
$(builddir)/cefclient: LD_INPUTS := $(OBJS) $(obj).target/javacef/libcef_dll_wrapper.a
$(builddir)/cefclient: TOOLSET := $(TOOLSET)
$(builddir)/cefclient: $(OBJS) $(obj).target/javacef/libcef_dll_wrapper.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/cefclient
# Add target alias
.PHONY: cefclient
cefclient: $(builddir)/cefclient

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/cefclient

