# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := chromium_loader
### Rules for action "build_java_files":
quiet_cmd_javacef_chromium_loader_gyp_chromium_loader_target_build_java_files = ACTION javacef_chromium_loader_gyp_chromium_loader_target_build_java_files $@
cmd_javacef_chromium_loader_gyp_chromium_loader_target_build_java_files = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd javacef; mkdir -p $(builddir)/javabin/org/embedded/browser; javac -cp "$(PWD)/javacef/java_resources/swt.jar" -encoding gb2312 -d "$(builddir)/javabin" src/org/embedded/browser/ChromeSettings.java src/org/embedded/browser/ChromeWindow.java src/org/embedded/browser/Chromium.java src/org/embedded/browser/CloseWindowListener.java src/org/embedded/browser/DownloadWindow.java src/org/embedded/browser/LoadStatusListener.java src/org/embedded/browser/NavStateListener.java src/org/embedded/browser/NewWindowListener.java src/org/embedded/browser/SampleWindow.java src/org/embedded/browser/TitleChangeListener.java

$(builddir)/javabin/org/embedded/browser/ChromeSettings.class: obj := $(abs_obj)
$(builddir)/javabin/org/embedded/browser/ChromeSettings.class: builddir := $(abs_builddir)
$(builddir)/javabin/org/embedded/browser/ChromeSettings.class: TOOLSET := $(TOOLSET)
$(builddir)/javabin/org/embedded/browser/ChromeSettings.class: javacef/src/org/embedded/browser/ChromeSettings.java javacef/src/org/embedded/browser/ChromeWindow.java javacef/src/org/embedded/browser/Chromium.java javacef/src/org/embedded/browser/CloseWindowListener.java javacef/src/org/embedded/browser/DownloadWindow.java javacef/src/org/embedded/browser/LoadStatusListener.java javacef/src/org/embedded/browser/NavStateListener.java javacef/src/org/embedded/browser/NewWindowListener.java javacef/src/org/embedded/browser/SampleWindow.java javacef/src/org/embedded/browser/TitleChangeListener.java FORCE_DO_CMD
	$(call do_cmd,javacef_chromium_loader_gyp_chromium_loader_target_build_java_files)
$(builddir)/javabin/org/embedded/browser/ChromeWindow.class $(builddir)/javabin/org/embedded/browser/Chromium.class $(builddir)/javabin/org/embedded/browser/CloseWindowListener.class $(builddir)/javabin/org/embedded/browser/DownloadWindow.class $(builddir)/javabin/org/embedded/browser/LoadStatusListener.class $(builddir)/javabin/org/embedded/browser/NavStateListener.class $(builddir)/javabin/org/embedded/browser/NewWindowListener.class $(builddir)/javabin/org/embedded/browser/SampleWindow.class $(builddir)/javabin/org/embedded/browser/TitleChangeListener.class: $(builddir)/javabin/org/embedded/browser/ChromeSettings.class
$(builddir)/javabin/org/embedded/browser/ChromeWindow.class $(builddir)/javabin/org/embedded/browser/Chromium.class $(builddir)/javabin/org/embedded/browser/CloseWindowListener.class $(builddir)/javabin/org/embedded/browser/DownloadWindow.class $(builddir)/javabin/org/embedded/browser/LoadStatusListener.class $(builddir)/javabin/org/embedded/browser/NavStateListener.class $(builddir)/javabin/org/embedded/browser/NewWindowListener.class $(builddir)/javabin/org/embedded/browser/SampleWindow.class $(builddir)/javabin/org/embedded/browser/TitleChangeListener.class: ;

all_deps += $(builddir)/javabin/org/embedded/browser/ChromeSettings.class $(builddir)/javabin/org/embedded/browser/ChromeWindow.class $(builddir)/javabin/org/embedded/browser/Chromium.class $(builddir)/javabin/org/embedded/browser/CloseWindowListener.class $(builddir)/javabin/org/embedded/browser/DownloadWindow.class $(builddir)/javabin/org/embedded/browser/LoadStatusListener.class $(builddir)/javabin/org/embedded/browser/NavStateListener.class $(builddir)/javabin/org/embedded/browser/NewWindowListener.class $(builddir)/javabin/org/embedded/browser/SampleWindow.class $(builddir)/javabin/org/embedded/browser/TitleChangeListener.class
action_javacef_chromium_loader_gyp_chromium_loader_target_build_java_files_outputs := $(builddir)/javabin/org/embedded/browser/ChromeSettings.class $(builddir)/javabin/org/embedded/browser/ChromeWindow.class $(builddir)/javabin/org/embedded/browser/Chromium.class $(builddir)/javabin/org/embedded/browser/CloseWindowListener.class $(builddir)/javabin/org/embedded/browser/DownloadWindow.class $(builddir)/javabin/org/embedded/browser/LoadStatusListener.class $(builddir)/javabin/org/embedded/browser/NavStateListener.class $(builddir)/javabin/org/embedded/browser/NewWindowListener.class $(builddir)/javabin/org/embedded/browser/SampleWindow.class $(builddir)/javabin/org/embedded/browser/TitleChangeListener.class

### Rules for action "generate_java_jni_headers":
quiet_cmd_javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers = ACTION javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers $@
cmd_javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd javacef; mkdir -p $(obj).$(TOOLSET)/chromium_loader/geni; javah -classpath "$(builddir)/javabin" -d "$(obj).$(TOOLSET)/chromium_loader/geni" org.embedded.browser.Chromium org.embedded.browser.DownloadWindow

$(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h: obj := $(abs_obj)
$(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h: builddir := $(abs_builddir)
$(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h: TOOLSET := $(TOOLSET)
$(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h: $(builddir)/javabin/org/embedded/browser/ChromeSettings.class $(builddir)/javabin/org/embedded/browser/Chromium.class $(builddir)/javabin/org/embedded/browser/DownloadWindow.class FORCE_DO_CMD
	$(call do_cmd,javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers)
$(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_DownloadWindow.h: $(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h
$(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_DownloadWindow.h: ;

all_deps += $(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h $(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_DownloadWindow.h
action_javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers_outputs := $(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_Chromium.h $(obj).$(TOOLSET)/$(TARGET)/geni/org_embedded_browser_DownloadWindow.h


### Generated for copy rule.
$(builddir)/java_resources/arrow_left.png: TOOLSET := $(TOOLSET)
$(builddir)/java_resources/arrow_left.png: javacef/java_resources/arrow_left.png FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/java_resources/arrow_left.png
$(builddir)/java_resources/arrow_refresh.png: TOOLSET := $(TOOLSET)
$(builddir)/java_resources/arrow_refresh.png: javacef/java_resources/arrow_refresh.png FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/java_resources/arrow_refresh.png
$(builddir)/java_resources/arrow_right.png: TOOLSET := $(TOOLSET)
$(builddir)/java_resources/arrow_right.png: javacef/java_resources/arrow_right.png FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/java_resources/arrow_right.png
$(builddir)/java_resources/page-loader.gif: TOOLSET := $(TOOLSET)
$(builddir)/java_resources/page-loader.gif: javacef/java_resources/page-loader.gif FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/java_resources/page-loader.gif
$(builddir)/java_resources/swt.jar: TOOLSET := $(TOOLSET)
$(builddir)/java_resources/swt.jar: javacef/java_resources/swt.jar FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/java_resources/swt.jar
$(builddir)/run_javacef_sample: TOOLSET := $(TOOLSET)
$(builddir)/run_javacef_sample: javacef/java_resources/run_javacef_sample FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/run_javacef_sample
javacef_chromium_loader_gyp_chromium_loader_target_copies = $(builddir)/java_resources/arrow_left.png $(builddir)/java_resources/arrow_refresh.png $(builddir)/java_resources/arrow_right.png $(builddir)/java_resources/page-loader.gif $(builddir)/java_resources/swt.jar $(builddir)/run_javacef_sample

DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSING_CEF_SHARED' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-Ijavacef \
	-Ijavacef/chromium_loader \
	-I$(JAVA_HOME)/include \
	-I$(JAVA_HOME)/include/linux \
	-I$(obj).$(TOOLSET)/$(TARGET)/geni

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSING_CEF_SHARED' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-Ijavacef \
	-Ijavacef/chromium_loader \
	-I$(JAVA_HOME)/include \
	-I$(JAVA_HOME)/include/linux \
	-I$(obj).$(TOOLSET)/$(TARGET)/geni

OBJS := \
	$(obj).target/$(TARGET)/javacef/cefclient/cefclient.o \
	$(obj).target/$(TARGET)/javacef/cefclient/binding_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_app.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_app_delegates.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_handler.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_renderer.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_switches.o \
	$(obj).target/$(TARGET)/javacef/cefclient/dialog_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/dom_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/performance_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/performance_test_tests.o \
	$(obj).target/$(TARGET)/javacef/cefclient/scheme_test.o \
	$(obj).target/$(TARGET)/javacef/cefclient/string_util.o \
	$(obj).target/$(TARGET)/javacef/cefclient/window_test.o \
	$(obj).target/$(TARGET)/javacef/chromium_loader/jni_tools.o \
	$(obj).target/$(TARGET)/javacef/cefclient/client_handler_gtk.o \
	$(obj).target/$(TARGET)/javacef/cefclient/resource_util_linux.o \
	$(obj).target/$(TARGET)/javacef/cefclient/window_test_gtk.o \
	$(obj).target/$(TARGET)/javacef/chromium_loader/chromium_loader_linux.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/javacef/libcef_dll_wrapper.a $(obj).target/javacef/gtk.stamp

# Make sure our actions/rules run before any of us.
$(OBJS): | $(action_javacef_chromium_loader_gyp_chromium_loader_target_build_java_files_outputs) $(action_javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers_outputs) $(javacef_chromium_loader_gyp_chromium_loader_target_copies)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/javacef/libchromium_loader.so: | $(action_javacef_chromium_loader_gyp_chromium_loader_target_build_java_files_outputs) $(action_javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers_outputs) $(javacef_chromium_loader_gyp_chromium_loader_target_copies)

# Preserve order dependency of special output on deps.
$(action_javacef_chromium_loader_gyp_chromium_loader_target_build_java_files_outputs) $(action_javacef_chromium_loader_gyp_chromium_loader_target_generate_java_jni_headers_outputs) $(javacef_chromium_loader_gyp_chromium_loader_target_copies): | $(obj).target/javacef/libcef_dll_wrapper.a $(obj).target/javacef/gtk.stamp

LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-rpath,.

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-rpath,. \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	$(PWD)/javacef/$(BUILDTYPE)/libcef.so \
	-lgmodule-2.0 \
	-lgtk-x11-2.0 \
	-lgdk-x11-2.0 \
	-latk-1.0 \
	-lgio-2.0 \
	-lpangoft2-1.0 \
	-lpangocairo-1.0 \
	-lgdk_pixbuf-2.0 \
	-lcairo \
	-lpango-1.0 \
	-lfreetype \
	-lfontconfig \
	-lgobject-2.0 \
	-lgthread-2.0 \
	-lrt \
	-lglib-2.0

$(obj).target/javacef/libchromium_loader.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/javacef/libchromium_loader.so: LIBS := $(LIBS)
$(obj).target/javacef/libchromium_loader.so: LD_INPUTS := $(OBJS) $(obj).target/javacef/libcef_dll_wrapper.a
$(obj).target/javacef/libchromium_loader.so: TOOLSET := $(TOOLSET)
$(obj).target/javacef/libchromium_loader.so: $(OBJS) $(obj).target/javacef/libcef_dll_wrapper.a FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/javacef/libchromium_loader.so
# Add target alias
.PHONY: chromium_loader
chromium_loader: $(builddir)/lib.target/libchromium_loader.so

# Copy this to the shared library output path.
$(builddir)/lib.target/libchromium_loader.so: TOOLSET := $(TOOLSET)
$(builddir)/lib.target/libchromium_loader.so: $(obj).target/javacef/libchromium_loader.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/lib.target/libchromium_loader.so
# Short alias for building this shared library.
.PHONY: libchromium_loader.so
libchromium_loader.so: $(obj).target/javacef/libchromium_loader.so $(builddir)/lib.target/libchromium_loader.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/lib.target/libchromium_loader.so

