# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libcef_dll_wrapper
DEFS_Debug := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSING_CEF_SHARED' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Debug := \
	-Ijavacef \
	-Ijavacef/chromium_loader

DEFS_Release := \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DUSE_X11=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DUSING_CEF_SHARED' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-pthread \
	-I/usr/include/glib-2.0 \
	-I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
	-I/usr/include/gtk-2.0 \
	-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include \
	-I/usr/include/atk-1.0 \
	-I/usr/include/cairo \
	-I/usr/include/gdk-pixbuf-2.0 \
	-I/usr/include/pango-1.0 \
	-I/usr/include/gio-unix-2.0/ \
	-I/usr/include/pixman-1 \
	-I/usr/include/freetype2 \
	-I/usr/include/libpng12 \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare

INCS_Release := \
	-Ijavacef \
	-Ijavacef/chromium_loader

OBJS := \
	$(obj).target/$(TARGET)/javacef/libcef_dll/transfer_util.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/wrapper/cef_byte_read_handler.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/wrapper/cef_stream_resource_handler.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/wrapper/cef_xml_object.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/wrapper/cef_zip_archive.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/wrapper/libcef_dll_wrapper.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/wrapper/libcef_dll_wrapper2.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/app_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/auth_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/before_download_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/binary_value_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/browser_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/browser_host_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/browser_process_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/client_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/command_line_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/completion_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/context_menu_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/context_menu_params_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/cookie_manager_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/cookie_visitor_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/domdocument_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/domevent_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/domevent_listener_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/domnode_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/domvisitor_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/dialog_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/dictionary_value_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/display_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/download_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/download_item_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/download_item_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/file_dialog_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/focus_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/frame_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/geolocation_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/geolocation_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/get_geolocation_callback_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/jsdialog_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/jsdialog_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/keyboard_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/life_span_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/list_value_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/load_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/menu_model_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/post_data_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/post_data_element_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/process_message_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/quota_callback_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/read_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/render_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/render_process_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/request_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/request_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/resource_bundle_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/resource_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/response_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/run_file_dialog_callback_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/scheme_handler_factory_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/scheme_registrar_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/stream_reader_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/stream_writer_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/string_visitor_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/task_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/task_runner_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/trace_client_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/urlrequest_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/urlrequest_client_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/v8accessor_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/v8context_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/v8exception_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/v8handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/v8stack_frame_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/v8stack_trace_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/v8value_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/web_plugin_info_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/web_plugin_info_visitor_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/web_plugin_unstable_callback_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/cpptoc/write_handler_cpptoc.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/xml_reader_ctocpp.o \
	$(obj).target/$(TARGET)/javacef/libcef_dll/ctocpp/zip_reader_ctocpp.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/javacef/gtk.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/javacef/libcef_dll_wrapper.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/javacef/libcef_dll_wrapper.a: LIBS := $(LIBS)
$(obj).target/javacef/libcef_dll_wrapper.a: TOOLSET := $(TOOLSET)
$(obj).target/javacef/libcef_dll_wrapper.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/javacef/libcef_dll_wrapper.a
# Add target alias
.PHONY: libcef_dll_wrapper
libcef_dll_wrapper: $(obj).target/javacef/libcef_dll_wrapper.a

# Add target alias to "all" target.
.PHONY: all
all: libcef_dll_wrapper

